version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build:
    docker:
      - image: circleci/node:fermium
    steps:
      - checkout
      - run: npm install
      - run: npm run check:style
      - run: node --version
