version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  check-style:
    docker:
      - image: circleci/node:fermium
    steps:
      - checkout
      - run: npm install
      - run: npm run check:style
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy/deploy_wictiunary-backend.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main
  review:
    jobs:
      - check-style:
          filters:
            branches:
              ignore:
                - main
