version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build:
    executor:
      name: node/default
      tag: '12.8.3'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run check:style
